image: Ubuntu

environment:
  ROS_WGET_BOOTCDREGTEST: https://iso.reactos.org/bootcdregtest/reactos-bootcdregtest-0.4.10-dev-121-gbd2f3d3-x86-gcc-lin-dbg.iso

version: sysreg2.appveyor.{build}
skip_branch_with_pr: true
clone_depth: 5
clone_folder: /sysreg2_workdir

install:
  - sh: sudo apt-get -q=2 update
  - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install libvirt-dev libxml2-dev > /dev/null
#
#   - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install cpu-checker > /dev/null
 # "INFO: Your CPU does not support KVM extensions" + "KVM acceleration can NOT be used"
#   - sh: sudo /usr/sbin/kvm-ok  || echo {kvm-ok} ExitStatus = $?

build_script:
  - sh: make

before_test:
  - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install libvirt-bin qemu-kvm > /dev/null
 # "The user `appveyor' is already a member of `libvirtd'."
#   - sh: sudo adduser $USER libvirtd
#
#   - sh: ll /usr/bin
#
#   - sh: touch bootcdregtest.iso
#
  - sh: wget --no-verbose --output-document=bootcdregtest.iso "$ROS_WGET_BOOTCDREGTEST"
#
# 
  - sh: ll bootcdregtest.iso

test_script:
  - sh: ./sysreg2  || echo {sysreg2} ExitStatus = $?

deploy: off
