image: Ubuntu

environment:
  ROS_WGET_BOOTCDREGTEST: https://iso.reactos.org/bootcdregtest/reactos-bootcdregtest-0.4.10-dev-121-gbd2f3d3-x86-gcc-lin-dbg.iso
  ROS_WGET_LOG2LINES: https://ci.appveyor.com/api/buildjobs/p2xv9370w47k2yc8/artifacts/log2lines-542-8f48ddc-gcc

version: sysreg2.appveyor.{build}
skip_branch_with_pr: true
clone_depth: 5
clone_folder: /sysreg2_workdir

# /sysreg2_workdir : all-in-one

install:
  - sh: sudo apt-get -q=2 update
  - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install libvirt-dev libxml2-dev > /dev/null
#
#   - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install cpu-checker > /dev/null
 # "INFO: Your CPU does not support KVM extensions" + "KVM acceleration can NOT be used"
#   - sh: sudo /usr/sbin/kvm-ok  || echo {kvm-ok} ExitStatus = $?

build_script:
  - sh: make

after_build:
  - sh: chmod u-w,go-x sysreg2
#
# 
  - sh: ll sysreg2

before_test:
  - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 install libvirt-bin qemu-kvm > /dev/null
 # "The user `appveyor' is already a member of `libvirtd'."
#   - sh: sudo adduser $USER libvirtd
#
#   - sh: ll /usr/bin
#
#   - sh: touch bootcdregtest.iso
#
  - sh: wget --no-verbose --output-document=bootcdregtest.iso "$ROS_WGET_BOOTCDREGTEST"
  - sh: chmod u-w bootcdregtest.iso
#
  - sh: wget --no-verbose --output-document=log2lines "$ROS_WGET_LOG2LINES"
  - sh: chmod u-w+x log2lines
#
# 
  - sh: ll bootcdregtest.iso log2lines

test_script:
#   - sh: ./sysreg2  || echo {sysreg2} ExitStatus = $?
#
  - sh: ./log2lines -h  || echo {log2lines} ExitStatus = $?
  - sh: ./log2lines -d bootcdregtest.iso -F
 # "time  ": to try later...
#
  - sh: ./sysreg2 | ./log2lines -d bootcdregtest.iso -m -M -s -U
  - sh: echo {sysreg2 log2lines} ExitStatus = "${PIPESTATUS[@]}"
#
#   - sh: set -o pipefail
#   - sh: ./sysreg2  | ./log2lines  || echo {sysreg2-log2lines} ExitStatus = $?

deploy: off
